LCD_PIN_DC = 8
LCD_PIN_CS = 9
LCD_PIN_CLK = 10
LCD_PIN_DIN = 11
LCD_PIN_RST = 12
LCD_PIN_BL = 13

SENSOR_PIN = 26

BUTTON_PIN_BOTTOM_RIGHT = 2
BUTTON_PIN_BOTTOM_LEFT = 3
BUTTON_PIN_TOP_RIGHT = 14
BUTTON_PIN_TOP_LEFT = 15
